import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComp from "./components/HeaderComp";
import FooterComp from "./components/FooterComp";
import ImagesBgComp from "./ImagesBgComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative z-0`}
      >
        <div className='div-responsividade relative z-10'>
          <HeaderComp />
          {children}
          <FooterComp />
        </div>
        <ImagesBgComp />
      </body>
    </html>
  );
}
